kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.name }}-{{ .Values.app.component }}-{{ .Values.github_secrets.name }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
stringData:
  # database-file-path: ${NAME}
  gh-org: {{ .Values.github_secrets.org }}
  gh-repo: {{ .Values.github_secrets.repo }}
  gh-access-token: {{ .Values.github_secrets.access_token }}
