apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
  name: {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.app.component }}
spec:
  lookupPolicy:
    local: true
  tags:
    - name: {{ .Values.image.image_tag }}
      from:
        kind: DockerImage
        name: {{ .Values.image.registry }}/{{ .Values.image.promote }}
      referencePolicy:
        type: Local
