apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name}}-{{ .Values.app.zone }}-{{ .Values.app.component }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
spec:
  #type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.api_port }}
      targetPort: {{ .Values.app.api_port }}
      protocol: TCP
      name: {{ .Values.app.api_port}}-tcp
  selector:
    #deployment: {{ .Values.app.name}}-{{ .Values.app.zone }}-{{ .Values.app.component }}
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
