apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress-{{ .Values.app.name }}-{{ .Values.app.zone }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
