kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.app.component }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: netapp-file-standard
