apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.app.component }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
stringData:
  # database-file-path: ${NAME}
  ampq_username: {{ .Values.ampq_secrets.username }}
  ampq_password: {{ .Values.ampq_secrets.password }}
  ampq_server: {{ .Values.ampq_secrets.domain }}
