name: Bias Correction

on:
  push:
    branches:
      - "main"
  # cron schedules are in UTC
  # this job should run at 9 am pst, which translates to 5 pm.
  schedule:
    - cron: '15 16 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: run-bias-correction

jobs:
  bias_correct:
    defaults:
      run:
        shell: bash
    name: 'Bias Correct ECMWF Forecast'
    runs-on: ubuntu-24.04
    environment: RUN
    env:
      OBJ_STORE_BUCKET: ${{ secrets.OBJ_STORE_BUCKET }}
      OBJ_STORE_SECRET: ${{ secrets.OBJ_STORE_SECRET }}
      OBJ_STORE_USER: ${{ secrets.OBJ_STORE_USER }}
      OBJ_STORE_HOST: ${{ secrets.OBJ_STORE_HOST }}

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
       fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - id: install_dependencies
      name: install python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install -r scripts/src/spatial-requirements.txt

    - id: bias_correction
      name: Bias Correct Forecast
      shell: bash
      run: |
        python scripts/src/BiasCorrection.py
