name: Pull Request Checks

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    defaults:
      run:
        shell: bash
    name: 'download dependencies'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      id: checkout
      with:
       fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - id: install_dependencies
      name: install python dependencies
      shell: bash
      run: |
        pip install -r requirements.txt

    - id: download_grib
      name: download grib files
      shell: bash
      environment: RUN
      env:
        OBJ_STORE_BUCKET=${{ secrets.OBJ_STORE_BUCKET }}
        OBJ_STORE_SECRET=${{ secrets.OBJ_STORE_SECRET }}
        OBJ_STORE_USER=${{ secrets.OBJ_STORE_USER }}
        OBJ_STORE_HOST=${{ secrets.OBJ_STORE_HOST }}
      run: | 
        python src/main.py
