name: SMAP Download

on:
  # push:
  #   branches:
  #     - "main"
  # cron schedules are in UTC
  # running at 6 am pst, which translates to 2 pm utc.
  # schedule:
  #   - cron: '00 14 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: run-smap-download

jobs:
  bias_correct:
    defaults:
      run:
        shell: bash
    name: 'Download SMAP'
    runs-on: ubuntu-22.04
    environment: RUN
    env:
      OBJ_STORE_BUCKET: ${{ secrets.OBJ_STORE_BUCKET }}
      OBJ_STORE_SECRET: ${{ secrets.OBJ_STORE_SECRET }}
      OBJ_STORE_USER: ${{ secrets.OBJ_STORE_USER }}
      OBJ_STORE_HOST: ${{ secrets.OBJ_STORE_HOST }}
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}

    steps:
    - uses: actions/checkout@v6
      id: checkout
      with:
       fetch-depth: 0

    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - id: install_dependencies
      name: install python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install -r scripts/src/requirements_smap.txt

    - name: Test Internet Connectivity
      run: curl -I https://urs.earthdata.nasa.gov

    - id: SMAP_download
      name: Download SMAP data
      shell: bash
      run: |
        python scripts/src/main_SMAP.py
