name: test remote execution

on:
  # push:
  #   branches:
  #     - "feat/daily-grib2-download"
  # cron schedules are in UTC
  # this job should run at 5.31 am pst, which translates to 1.31 pm.
  # schedule:
  #   - cron: '31 13 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: do-something

jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
          DATESTR: ${{ github.event.client_payload.idem_key }}
        name: Do Something
        run: |
          echo Doing Something...
          echo Incomming message: $MESSAGE
          echo Date is: $DATESTR
