name: test remote execution

on:
  # push:
  #   branches:
  #     - "feat/daily-grib2-download"
  # cron schedules are in UTC
  # this job should run at 5.31 am pst, which translates to 1.31 pm.
  # schedule:
  #   - cron: '31 13 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: do-something

jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        name: Do Something
        run: |
          echo Doing Something...
          echo Incomming message: $MESSAGE
          echo "payload as json: ${{ toJson(github.event.client_payload) }} | jq ."
          echo ${{ toJson(github.event.client_payload) }} > payload.json
          date=$(cat payload.json | tr  -d '\n' | jq .idem_key | tr -d '"')
          echo date is $date
          jsonstr=$(${{ toJson(github.event.client_payload) }} | tr -d '\n')
          echo jsonstr: $jsonstr
          $(cat junk.txt | tr  -d '\n' | jq .idem_key | tr -d '"')
          var=$(${{ toJson(github.event.client_payload) }} | jq .message)
          echo "var: $var"
          echo "payload non json: ${{ github.event.client_payload }}"
